#!/bin/bash

set -e

lb config noauto \
    --architectures amd64 \
    --distribution bookworm \
    --archive-areas "main contrib non-free non-free-firmware" \
    --initramfs live-boot \
    --bootappend-live "boot=live components quiet splash" \
    --binary-images iso-hybrid \
    --bootloader grub2 \
    --iso-publisher "Stupix Project" \
    --iso-volume "Stupix Live" \
    --apt-recommends false \
    --initsystem systemd \
    --keyring-packages debian-archive-keyring \
    --linux-packages none \
    "${@}"
